[project]
name = "make-my-blogs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-ollama>=0.2.3",
    "langchain>=0.3.18",
]
